In [1]:
#!/usr/bin/env python

In [2]:
import numpy as np
from numpy.linalg import norm, eig, matrix_power, inv
np.set_printoptions(precision=4, suppress=True)

Define a symmetric (and thus diagonalizable) 3×3 matrix

In [3]:
A = np.array([
    [2, 0, 0],
    [0, 3, 1],
    [0, 1, 3]
], dtype=float)

In [4]:
B = np.array([
    [4, 0],
    [3, 0],
    [0, 5]
], dtype=float)

Eigendecomposition: A = VΛVˉᣳ

In [5]:
λ, V = eig(A)
Λ = np.diag(λ)
Vˉᣳ = inv(V)  # inverse of V
v = V[:,0].reshape(-1,1) # the dominant eigenvector

Power to raise A

In [6]:
n = 100 

Naive method: repeated matrix power

In [7]:
A_naive = matrix_power(A, n)

Diagonalization trick: Aⁿ = VΛⁿVˉᣳ

In [8]:
Λⁿ = np.diag(λ**n)
Aᣳᵒᵒ = V @ Λⁿ @ Vˉᣳ

Output comparison

In [9]:
print("Naive Aⁿ:\n", A_naive)
print("\nSmart Aⁿ using VΛⁿVˉᣳ:\n", Aᣳᵒᵒ)

Naive Aⁿ:
 [[1.2677e+30 0.0000e+00 0.0000e+00]
 [0.0000e+00 8.0347e+59 8.0347e+59]
 [0.0000e+00 8.0347e+59 8.0347e+59]]

Smart Aⁿ using VΛⁿVˉᣳ:
 [[1.2677e+30 0.0000e+00 0.0000e+00]
 [0.0000e+00 8.0347e+59 8.0347e+59]
 [0.0000e+00 8.0347e+59 8.0347e+59]]


--------------------

In [10]:
C = Aᣳᵒᵒ @ B
C = C/norm(C, axis=0)
print('\nThe dominant eigenvector of the msg\n',v)
print('\nYour mind after 100 exposures\n',C)


The dominant eigenvector of the msg
 [[0.    ]
 [0.7071]
 [0.7071]]

Your mind after 100 exposures
 [[0.     0.    ]
 [0.7071 0.7071]
 [0.7071 0.7071]]
