In [1]:
#!/usr/bin/env python
#
from sklearn.preprocessing import MinMaxScaler
import numpy as np
#
X = np.array([[3,0,400],[2,1,200],[2,2,500],[1,1,100]])
print(X)

[[  3   0 400]
 [  2   1 200]
 [  2   2 500]
 [  1   1 100]]


In [2]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
print(X)

[[1.   0.   0.75]
 [0.5  0.5  0.25]
 [0.5  1.   1.  ]
 [0.   0.5  0.  ]]
