In [1]:
#!/usr/bin/env python

In [2]:
from sklearn import preprocessing
from matplotlib.ticker import PercentFormatter
import numpy as np

In [3]:
X = np.array([[3,0,400],[2,1,200],[2,2,500],[1,1,100]])
print(X)

[[  3   0 400]
 [  2   1 200]
 [  2   2 500]
 [  1   1 100]]


In [4]:
X = preprocessing.scale(X)
print(X)

[[ 1.41421356 -1.41421356  0.63245553]
 [ 0.          0.         -0.63245553]
 [ 0.          1.41421356  1.26491106]
 [-1.41421356  0.         -1.26491106]]


In [5]:
print(np.mean(X,axis=0))
print(np.std(X,axis=0))

[0. 0. 0.]
[1. 1. 1.]
