In [1]:
#!/usr/bin/env python

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
X = np.array([	[  4.,  -9.2], 
				[ -4.,  -6.], 
				[ 12., -10.], 
				[ -1., -16.]])

In [4]:
y = np.array( [	[ -5.],
				[ -9.],
				[  2.], 
				[-17.]])

In [5]:
Ⅱ = np.ones((4,1))
Φ = np.hstack((X,Ⅱ))

Closed form solution 

In [6]:
w = np.linalg.inv(Φ.T.dot(Φ)).dot(Φ.T.dot(y))
print(w)

[[0.95770147]
 [1.08362577]
 [1.27766637]]


In [7]:
print('Predicted labels vs True Labels Compared Side by Side')
print(np.hstack((Φ.dot(w), y)))

Predicted labels vs True Labels Compared Side by Side
[[ -4.86088482  -5.        ]
 [ -9.0548941   -9.        ]
 [  1.93382629   2.        ]
 [-17.01804737 -17.        ]]


----------------- Using a library

In [8]:
reg = LinearRegression().fit(X, y)
print(reg.coef_)
print(reg.intercept_)

[[0.95770147 1.08362577]]
[1.27766637]


In [9]:
pred_y = reg.predict(X)
print('Predicted labels')
print(pred_y)

Predicted labels
[[ -4.86088482]
 [ -9.0548941 ]
 [  1.93382629]
 [-17.01804737]]
