In [1]:
#!/usr/bin/env python

In [2]:
import autograd.numpy as np
from autograd import grad

In [3]:
y = np.array([[2], [5]])
ӏ = np.array([[1], [1]])
x = np.random.random((2, 1))
w = np.array([[7], [8]])

Problem 1

In [4]:
def f(x,y,ӏ):
    return np.dot(np.transpose(y), x) + np.dot(np.transpose(x), ӏ)

In [5]:
grad_foo = grad(f)

In [6]:
print("Autograd: \n", grad_foo(x,y,ӏ))
print("Theoretical: \n", np.array([[3], [6]]))

Autograd: 
 [[3.]
 [6.]]
Theoretical: 
 [[3]
 [6]]


Problem 2

In [7]:
A = np.array([	[2, 1], 
				[1, 1]])
def f(x, A):
    return np.dot(np.dot(np.transpose(x), A), x)

In [8]:
def ߜf(x, A):
	return 2*A.dot(x)

In [9]:
grad_foo = grad(f)

In [10]:
print("Autograd: \n", grad_foo(x, A))
print("Theoretical: \n", ߜf(x, A))

Autograd: 
 [[2.48787638]
 [1.45698188]]
Theoretical: 
 [[2.48787638]
 [1.45698188]]


Problem 3

In [11]:
A = np.array([	[4, 0], 
				[1, 1]])
def f(x, A):
    return np.exp(np.dot(np.dot(np.transpose(x), A), x))

In [12]:
def ߜf(x, A):
	v = (A + np.transpose(A)).dot(x)
	return f(x,A)*v

In [13]:
grad_foo = grad(f)
print("Autograd: \n", grad_foo(x, A))
print("Theoretical: \n", ߜf(x, A))

Autograd: 
 [[14.65878053]
 [ 3.18260398]]
Theoretical: 
 [[14.65878053]
 [ 3.18260398]]


Problem 4

In [14]:
A = np.array([	[4, 0], 
				[1, 1]])
def eˉᵂˣ(w,x):
	return np.exp(np.dot(np.transpose(w), x))

In [15]:
def f(x, w):
    return np.linalg.inv(1 + eˉᵂˣ(w,x))

In [16]:
def ߜf(x, w):
	return (eˉᵂˣ(w,x)/(1 + eˉᵂˣ(w,x))**2)*w

In [17]:
grad_foo = grad(f)
print("Autograd: \n", grad_foo(x, w))
print("Theoretical: \n", ߜf(x, w))

Autograd: 
 [[-0.03417007]
 [-0.0390515 ]]
Theoretical: 
 [[0.03417007]
 [0.0390515 ]]
