In [1]:
#!/usr/bin/env python
import numpy as np

Define the matrix

In [2]:
A = np.array([
    [4, 2],
    [2, 3]
], dtype=float)

Eigendecomposition

In [3]:
λ, V = np.linalg.eigh(A)  # Since A is symmetric, use eigh

Sort eigenvalues and eigenvectors from largest to smallest for clarity

In [4]:
idx = np.argsort(λ)[::-1]
λ = λ[idx]
V = V[:, idx]

In [5]:
print("Eigenvalues:", λ)
print("Eigenvectors (columns):\n", V)

Eigenvalues: [5.56155281 1.43844719]
Eigenvectors (columns):
 [[-0.78820544  0.61541221]
 [-0.61541221 -0.78820544]]


Full reconstruction

In [6]:
A_full = λ[0] * np.outer(V[:, 0], V[:, 0]) + λ[1] * np.outer(V[:, 1], V[:, 1])
print("\nFull reconstruction A:")
print(np.round(A_full, 4))


Full reconstruction A:
[[4. 2.]
 [2. 3.]]


Low-rank reconstruction (setting λ2 = 0)

In [7]:
A_low_rank = λ[0] * np.outer(V[:, 0], V[:, 0])
print("\nLow-rank reconstruction A (λ2 = 0):")
print(np.round(A_low_rank, 4))


Low-rank reconstruction A (λ2 = 0):
[[3.4552 2.6977]
 [2.6977 2.1063]]


Difference

In [8]:
print("\nDifference between original A and low-rank reconstruction:")
print(np.round(A - A_low_rank, 4))


Difference between original A and low-rank reconstruction:
[[ 0.5448 -0.6977]
 [-0.6977  0.8937]]
