In [1]:
#!/usr/bin/env python
import numpy as np
from numpy import diag
from numpy.linalg import eig, inv
from scipy.linalg import null_space

Define the matrix A

In [2]:
A = np.array([[-6, 3],
              [4, 5]])

Eigenvalues and eigenvectors 

In [3]:
[λ,V] = eig(A)
print(λ)
print(V)

[-7.  6.]
[[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


Null Space

In [4]:
print(null_space(V.T))

[]


Diagonalization

In [5]:
Σ = diag(λ)
Vˉᣳ = inv(V)
print(V @ Σ @ Vˉᣳ)

[[-6.  3.]
 [ 4.  5.]]


Not symmetric

In [6]:
print(V @ Σ @ V.T)

[[-5.94705882  3.51176471]
 [ 3.51176471  4.94705882]]
