In [1]:
#!/usr/bin/env python

In [2]:
import numpy as np
from numpy import array
from numpy import trace

In [3]:
v = array([[1],[2],[3]])
print(v)

[[1]
 [2]
 [3]]


In [4]:
u = array([[3],[1],[4]])
print(u)

[[3]
 [1]
 [4]]


In [5]:
A = array([[1,2,3],[3,2,1],[3,1,1]])
print(A)

[[1 2 3]
 [3 2 1]
 [3 1 1]]


outer product $u v^{\top}$

In [6]:
print(u.dot(v.T))
print(u @ v.T)

[[ 3  6  9]
 [ 1  2  3]
 [ 4  8 12]]
[[ 3  6  9]
 [ 1  2  3]
 [ 4  8 12]]


inner/dot product $v^{\top} v$

In [7]:
print(v.T.dot(v))
print(v.T @ v)

[[14]]
[[14]]


$x^{\top} A x$

In [8]:
print(v.T.dot(A).dot(v))
print(v.T @ A @v)

[[58]]
[[58]]


hadamard

In [9]:
print(v*u)

[[ 3]
 [ 2]
 [12]]


matrix inner product

In [10]:
print(trace(A.dot(A.T)))

39
