In [1]:
#!/usr/bin/env python
import numpy as np
from numpy import array
from numpy import trace

v = array([[1],[2],[3]])
print(v)

[[1]
 [2]
 [3]]


In [2]:
u = array([[3],[1],[4]])
print(u)

[[3]
 [1]
 [4]]


In [3]:
A = array([[1,2,3],[3,2,1],[3,1,1]])
print(A)

[[1 2 3]
 [3 2 1]
 [3 1 1]]


outer product $u v^{\top}$

In [4]:
print(u.dot(v.T))

[[ 3  6  9]
 [ 1  2  3]
 [ 4  8 12]]


inner/dot product $v^{\top} v$

In [5]:
print(v.T.dot(v))

[[14]]


$x^{\top} A x$

In [6]:
print(v.T.dot(A).dot(v))

[[58]]


hadamard

In [7]:
print(v*u)

[[ 3]
 [ 2]
 [12]]


matrix inner product

In [8]:
print(trace(A.dot(A.T)))

39
